# GitHub Actions per deployment RECORP senza build process
name: Deploy RECORP Static Site

on:
  push:
    branches: ['main']
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: 'pages'
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Replace environment variables in files
        run: |
          # 🔧 SOSTITUISCE I PLACEHOLDER CON I VALORI SICURI
          echo "🔄 Sostituzione variabili ambiente..."
          
          # Sostituisce i placeholder nel file supabase-config.js
          if [ -f "supabase-config.js" ]; then
            # Sostituisce PLACEHOLDER_SUPABASE_URL con il valore del secret
            sed -i "s|PLACEHOLDER_SUPABASE_URL|${{ secrets.VITE_SUPABASE_URL }}|g" supabase-config.js
            
            # Sostituisce PLACEHOLDER_SUPABASE_ANON_KEY con il valore del secret  
            sed -i "s|PLACEHOLDER_SUPABASE_ANON_KEY|${{ secrets.VITE_SUPABASE_ANON_KEY }}|g" supabase-config.js
            
            echo "✅ Placeholder sostituiti in supabase-config.js"
            
            # Verifica che la sostituzione sia avvenuta (senza mostrare i valori)
            if ! grep -q "PLACEHOLDER_" supabase-config.js; then
              echo "✅ Tutti i placeholder sono stati sostituiti correttamente"
            else
              echo "❌ Alcuni placeholder non sono stati sostituiti"
              exit 1
            fi
          else
            echo "❌ File supabase-config.js non trovato"
            exit 1
          fi
          
          echo "✅ Configurazione completata per deploy sicuro"

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # 📁 Upload della cartella corrente (root del progetto)
          path: '.'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4